sudo: false
branches:
  only:
    - master
    - /^v.*$/ # Tagged builds (Travis branch name = tag name)
jobs:
  include:
    - stage: Test and Deploy
      language: node_js
      node_js: "14"
      script:
        # Ensure that you can build and tests pass in Node 6+
        
        - nvm use 14
        - npm run build

        - nvm install 12
        - nvm use 12
        - npm run build

        - nvm install 10
        - nvm use 10
        - npm run build

        - nvm install 8
        - nvm use 8
        - npm run build

        - npm run coveralls
      deploy: # Can't use npm provider because you need to publish the build folder
        provider: script
        skip_cleanup: true # Preserve the build so it can be published
        script:
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >>
          $HOME/.npmrc && npm publish build
        on:
          tags: true # Only deploy to NPM on tagged commits (new versions)
